name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Deploying to Edmund
        uses: appleboy/ssh-action@master #an action made to control linux servers
        with: #setting secrets
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ vars.MAIN_BRANCH }}
            git pull
            npm install
            npm run build
            exit
